### ISSUE TITLE
About the training process

### ISSUE THREAD

**Issue by abcdvzz** [abhimanyudubey/confusion#3]
I tried to implement your work of models/cub/bilinear_vgg/.
After I executed the command ./train.py .... --confusion '{"l1" : 1, "l2": 0.005}' \
--entropic, I got the model.prototxt. However, I cannot see the difference between this prototxt with the original one.
Did I do something wrong? Could you please tell me how to implement the bilinear pooling experiment of your paper? Thank you very much.

**Comment by abcdvzz** [comment]
Oh I got the reason. However, which layer should be written in the parameter of --confusion?

**Comment by abcdvzz** [comment]
emmm... And where do I modify the regularization parameter λ？

**Comment by abhimanyudubey** [comment]
Hi @abcdvzz, you should use the confusion typically on the last (logit) layer of the network, but it should provide moderate improvements (with very small λ of around ``10e-4`` to ``10e-5``) for intermediate layers as well. 

The formula explored in the ECCV paper can be replicated with the command:
```
./train.py .... --confusion '{"final_layer_name": 0.01}' 
```
The parameters to the ``--confusion`` argument are basically the layer name and the weight (λ), which in this case are ``final_layer_name`` and ``0.01``.  The README already covers this usage.
