### ISSUE TITLE
pytorch loss

### ISSUE THREAD

**Issue by twmht** [abhimanyudubey/confusion#8]
Hi,

there are two losses (PairwiseConfusion and  EntropicConfusion) defined in pytorch (https://github.com/abhimanyudubey/confusion/blob/master/confusion_pytorch/__init__.py), but the names confuse me.

which one should I use?

from the paper, EQ(5) is Euclidean Confusion, is this refer to PairwiseConfusion?

Where can I find the entropy confusion from the paper?

**Comment by abhimanyudubey** [comment]
Hi, the entropic confusion is described in this paper: http://papers.nips.cc/paper/7344-maximum-entropy-fine-grained-classification. You can try out both, hopefully, they should both provide improvements.
