### ISSUE TITLE
Ask for help， Compile error! 

### ISSUE THREAD

**Issue by BaofengZan** [abhimanyudubey/confusion#9]
Hi， When I compiled caffe, the following error occurred. My platform is ubuntu 16.04, cuda 8.0 and cudnn v6.
**CXX/LD -o .build_release/tools/compute_image_mean.bin
.build_release/lib/libcaffe.so: undefined reference to `cufftPlanMany'

.build_release/lib/libcaffe.so: undefined reference to `cufftExecD2Z'

.build_release/lib/libcaffe.so: undefined reference to `cufftExecC2R'

.build_release/lib/libcaffe.so: undefined reference to `cufftExecR2C'

.build_release/lib/libcaffe.so: undefined reference to `cufftExecZ2D'

collect2: error: ld returned 1 exit status**

**Comment by SpicyChicken4L** [comment]
You may follow the instructions on [https://github.com/gy20073/compact_bilinear_pooling/tree/master/caffe-20160312](url), seems like something is missing about cufft
